function varargout=sym_gelli_rhs(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_gelli_rhs_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_gelli_rhs_rhs_1_0(x,xp,xt,xpt,G,Q,tau,x_d,xp_d,xt_d,xpt_d,G_d,Q_d,tau_d)
%SYM_GELLI_RHS_RHS_1_0
%    [OUT1,OUT2] = SYM_GELLI_RHS_RHS_1_0(X,XP,XT,XPT,G,Q,TAU,X_D,XP_D,XT_D,XPT_D,G_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Apr-2022 20:41:53

out1 = xp;
if nargout > 1
    out2 = -x-tanh(G.*xt.*1.0e+1).*4.238233339959258-xp./Q;
end


function [out1,out2] = sym_gelli_rhs_rhs_1_1(x,xp,xt,xpt,G,Q,tau,x_d,xp_d,xt_d,xpt_d,G_d,Q_d,tau_d)
%SYM_GELLI_RHS_RHS_1_1
%    [OUT1,OUT2] = SYM_GELLI_RHS_RHS_1_1(X,XP,XT,XPT,G,Q,TAU,X_D,XP_D,XT_D,XPT_D,G_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Apr-2022 20:41:53

out1 = xp_d;
if nargout > 1
    out2 = -x_d+(tanh(G.*xt.*1.0e+1).^2-1.0).*(G.*xt_d.*1.0e+1+G_d.*xt.*1.0e+1).*4.238233339959258-xp_d./Q+1.0./Q.^2.*Q_d.*xp;
end


function [out1,out2] = sym_gelli_rhs_rhs_1_2(x,xp,xt,xpt,G,Q,tau,x_d,xp_d,xt_d,xpt_d,G_d,Q_d,tau_d)
%SYM_GELLI_RHS_RHS_1_2
%    [OUT1,OUT2] = SYM_GELLI_RHS_RHS_1_2(X,XP,XT,XPT,G,Q,TAU,X_D,XP_D,XT_D,XPT_D,G_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Apr-2022 20:41:53

out1 = 0.0;
if nargout > 1
    t2 = G.*xt.*1.0e+1;
    t3 = tanh(t2);
    t4 = t3.^2;
    t5 = t4-1.0;
    out2 = 1.0./Q.^3.*Q_d.^2.*xp.*-2.0-t3.*t5.*(G.*xt_d.*1.0e+1+G_d.*xt.*1.0e+1).^2.*8.476466679918516+G_d.*t5.*xt_d.*8.476466679918516e+1+1.0./Q.^2.*Q_d.*xp_d.*2.0;
end


function [out1,out2] = sym_gelli_rhs_rhs_1_3(x,xp,xt,xpt,G,Q,tau,x_d,xp_d,xt_d,xpt_d,G_d,Q_d,tau_d)
%SYM_GELLI_RHS_RHS_1_3
%    [OUT1,OUT2] = SYM_GELLI_RHS_RHS_1_3(X,XP,XT,XPT,G,Q,TAU,X_D,XP_D,XT_D,XPT_D,G_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Apr-2022 20:41:53

out1 = 0.0;
if nargout > 1
    t2 = G.*xt.*1.0e+1;
    t3 = G.*xt_d.*1.0e+1;
    t4 = G_d.*xt.*1.0e+1;
    t5 = tanh(t2);
    t8 = t3+t4;
    t6 = t5.^2;
    t9 = t8.^3;
    t7 = t6-1.0;
    out2 = t7.^2.*t9.*8.476466679918516+1.0./Q.^4.*Q_d.^3.*xp.*6.0-1.0./Q.^3.*Q_d.^2.*xp_d.*6.0+t6.*t7.*t9.*1.695293335983703e+1-G_d.*t5.*t7.*t8.*xt_d.*5.08588000795111e+2;
end


function [out1,out2] = sym_gelli_rhs_rhs_1_4(x,xp,xt,xpt,G,Q,tau,x_d,xp_d,xt_d,xpt_d,G_d,Q_d,tau_d)
%SYM_GELLI_RHS_RHS_1_4
%    [OUT1,OUT2] = SYM_GELLI_RHS_RHS_1_4(X,XP,XT,XPT,G,Q,TAU,X_D,XP_D,XT_D,XPT_D,G_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Apr-2022 20:41:53

out1 = 0.0;
if nargout > 1
    t2 = G.*xt.*1.0e+1;
    t3 = G.*xt_d.*1.0e+1;
    t4 = G_d.*xt.*1.0e+1;
    t5 = tanh(t2);
    t8 = t3+t4;
    t6 = t5.^2;
    t10 = t8.^2;
    t7 = t6-1.0;
    t11 = t10.^2;
    t9 = t7.^2;
    out2 = t5.^3.*t7.*t11.*(-3.390586671967407e+1)-1.0./Q.^5.*Q_d.^4.*xp.*2.4e+1+1.0./Q.^4.*Q_d.^3.*xp_d.*2.4e+1-t5.*t9.*t11.*6.781173343934813e+1+G_d.*t9.*t10.*xt_d.*1.017176001590222e+3-G_d.^2.*t5.*t7.*xt_d.^2.*1.017176001590222e+4+G_d.*t6.*t7.*t10.*xt_d.*2.034352003180444e+3;
end


function [out1,out2] = sym_gelli_rhs_rhs_1_5(x,xp,xt,xpt,G,Q,tau,x_d,xp_d,xt_d,xpt_d,G_d,Q_d,tau_d)
%SYM_GELLI_RHS_RHS_1_5
%    [OUT1,OUT2] = SYM_GELLI_RHS_RHS_1_5(X,XP,XT,XPT,G,Q,TAU,X_D,XP_D,XT_D,XPT_D,G_D,Q_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Apr-2022 20:41:54

out1 = 0.0;
if nargout > 1
    t2 = G_d.^2;
    t3 = xt_d.^2;
    t4 = G.*xt.*1.0e+1;
    t5 = G.*xt_d.*1.0e+1;
    t6 = G_d.*xt.*1.0e+1;
    t7 = tanh(t4);
    t10 = t5+t6;
    t8 = t7.^2;
    t12 = t10.^3;
    t13 = t10.^5;
    t9 = t8-1.0;
    t11 = t9.^2;
    out2 = t9.^3.*t13.*6.781173343934813e+1+t8.^2.*t9.*t13.*6.781173343934813e+1+1.0./Q.^6.*Q_d.^5.*xp.*1.2e+2-1.0./Q.^5.*Q_d.^4.*xp_d.*1.2e+2+t8.*t11.*t13.*3.729645339164147e+2+t2.*t3.*t10.*t11.*5.08588000795111e+4-G_d.*t7.*t11.*t12.*xt_d.*1.356234668786963e+4+t2.*t3.*t8.*t9.*t10.*1.017176001590222e+5-G_d.*t7.^3.*t9.*t12.*xt_d.*6.781173343934813e+3;
end

